name: build-firmware
run-name: ${{ github.actor }} is building firmware.
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create bin directory
        run: mkdir -p ~/.local/bin
      - name: Install arduino CLI
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/.local/bin sh
      - name: Install build dependencies
        run: make install_libs
      - name: Build firmware
        run: make all
      - name: Create firmware archive
        run: cd build/; zip fw_bundle.zip *.bin
      - uses: JasonEtco/upload-to-release@master
        with:
          args: build/fw_bundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
