# Workflow to deploy binaries to a zip file in release

name: deploy-binaries
run-name: ${{ github.actor }} is building firmware.
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Create bin directory
        run: mkdir -p ~/.local/bin
      - name: Install arduino CLI
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/.local/bin sh
      - name: Install build dependencies
        run: make install_libs
      - name: Build firmware
        run: make all
      - name: Build firmware (debug)
        run: make DEBUG=true all
      - name: Create firmware archive
        run: cd build/; zip fw_bundle.zip *.bin
      - name: Deploy release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./build/fw_bundle.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
